"use client";
import type { FinanceAccountRowViewModel } from "../../lib/modules/finance/accounts-view-model";
import type { FinanceState, FinanceTransactionRecord } from "../../lib/modules/finance/native-types";
import { accountBalanceSource, accountBalanceExplanation, accountDate, signedAccountTransaction, findAccountTransferCandidates } from "../../lib/modules/finance/account-details";
import { DetailTabPanel } from "../operational/DetailTabs";
import UnigentamosIcon from "../icons/UnigentamosIcon";
import type { FinanceOperation } from "./FinanceMutationDialog";
import { money } from "./FinancePrimitives";

function DateBadge({value}:{value:string}){const date=new Date(`${value}T12:00:00Z`);return <time className="finance-activity-date" dateTime={value} title={accountDate(value)}><span>{date.toLocaleDateString("en-US",{month:"short",timeZone:"UTC"})}</span><strong>{date.getUTCDate()}</strong><small>{date.getUTCFullYear()}</small></time>}
function Activity({items,onReview}:{items:FinanceTransactionRecord[];onReview?:(id:string)=>void}){
 return <div className="finance-account-ledger">{items.map(item=>{const amount=signedAccountTransaction(item);return <article className="finance-account-ledger-row" key={item.id}><DateBadge value={item.occurredOn}/><a className="finance-activity-description" href={`/admin/finance/transactions?selected=${encodeURIComponent(item.id)}`}><strong>{item.merchant}</strong><span><span className="finance-activity-category">{item.category||"Uncategorized"}</span>{item.status==="pending"&&<small>Pending</small>}</span>{item.memo&&<small className="finance-activity-memo">{item.memo}</small>}</a><strong className={`finance-activity-amount ${amount>0?"is-positive":amount<0?"is-negative":""}`}>{money(amount,{sign:true,cents:true})}</strong>{onReview&&<button className="finance-review-entry" onClick={()=>onReview(item.id)} title={`Reconcile ${item.merchant}`} aria-label={`Reconcile ${item.merchant}`}><UnigentamosIcon role="check" size={17}/><span>Reconcile</span></button>}</article>})}</div>
}
function Fact({icon,label,children}:{icon:string;label:string;children:React.ReactNode}){return <div className="finance-account-fact"><span><UnigentamosIcon role={icon} size={17}/>{label}</span><strong>{children}</strong></div>}
export default function FinanceAccountDetails({row,state,tab,onOperation}:{row:FinanceAccountRowViewModel;state:FinanceState;tab:string;onOperation:(op:FinanceOperation,selection:{kind:"account"|"transaction";id:string})=>void}){
 const account=state.accounts.find(a=>a.id===row.account.id),selection={kind:"account" as const,id:row.account.id};
 const transactions=state.transactions.filter(t=>!t.archivedAt&&t.accountId===row.account.id).sort((a,b)=>b.occurredOn.localeCompare(a.occurredOn)||a.merchant.localeCompare(b.merchant));
 const positives=transactions.filter(t=>signedAccountTransaction(t)>0),negatives=transactions.filter(t=>signedAccountTransaction(t)<0),unreviewed=transactions.filter(t=>!t.reviewed||t.status==="pending");
 const transfers=state.transfers.filter(t=>!t.archivedAt&&(t.fromAccountId===row.account.id||t.toAccountId===row.account.id)).sort((a,b)=>b.occurredOn.localeCompare(a.occurredOn));
 const candidates=findAccountTransferCandidates(state,row.account.id),imports=state.importBatches.filter(b=>b.accountId===row.account.id).slice().reverse();
 const source=accountBalanceSource(account),connected=Boolean(account?.bankLink||account?.coinbaseLink);
 const panel=(id:string,children:React.ReactNode)=><DetailTabPanel tabsId="finance-object-tabs" tabId={id} active={tab===id} className="finance-account-detail-panel">{children}</DetailTabPanel>;
 return <div className="finance-account-details">
 {panel("overview",<><div className="finance-account-facts"><Fact icon="wallet" label="Current balance">{money(row.account.balance,{cents:true})}</Fact><Fact icon="clock" label={connected?"Last retrieved":"Balance dated"}>{accountDate(account?.balanceRetrievedAt||account?.balanceAsOf,true)}</Fact><Fact icon="banknote" label="Positive transactions"><span className="is-positive">{money(positives.reduce((s,t)=>s+signedAccountTransaction(t),0),{sign:true,cents:true})}</span><small>{positives.length} {positives.length === 1 ? "entry" : "entries"}</small></Fact><Fact icon="banknote" label="Negative transactions"><span className="is-negative">{money(negatives.reduce((s,t)=>s+signedAccountTransaction(t),0),{sign:true,cents:true})}</span><small>{negatives.length} {negatives.length === 1 ? "entry" : "entries"}</small></Fact></div><section className="finance-account-source"><div><UnigentamosIcon role={connected?"link":"edit"} size={20}/><span><small>Balance source</small><strong>{source}</strong></span><span className="finance-account-source-state">{connected?"Connected":"Recorded"}</span></div><p>{accountBalanceExplanation(account)}</p>{!connected&&<button className="finance-action" onClick={()=>onOperation("balance",selection)}>Update balance</button>}</section><p className="finance-account-scope-note">Transaction totals cover the activity currently saved for this account, including pending entries.</p></>)}
 {panel("transactions",transactions.length?<Activity items={transactions}/>:<div className="finance-account-empty"><UnigentamosIcon role="banknote"/><h3>No transactions yet</h3><p>Add a transaction, import a statement, or sync a connected account.</p></div>)}
 {panel("reconcile",<><div className="finance-account-section-title"><UnigentamosIcon role="review"/><div><h3>{unreviewed.length?`${unreviewed.length} to review`:"Everything is reconciled"}</h3><p>Check the amount and details against your account. Pending entries stay here until they clear.</p></div></div><Activity items={unreviewed} onReview={id=>onOperation("transaction_review",{kind:"transaction",id})}/></>)}
 {panel("transfers",<><div className="finance-account-inline-actions"><button className="finance-action" onClick={()=>onOperation("transfer",selection)}><UnigentamosIcon role="plus" size={16}/>Record transfer</button><button className="finance-action" onClick={()=>onOperation("savings",selection)}>Savings movement</button></div>{transfers.map(t=>{const outgoing=t.fromAccountId===row.account.id,peer=state.accounts.find(a=>a.id===(outgoing?t.toAccountId:t.fromAccountId));return <article className="finance-account-ledger-row" key={t.id}><DateBadge value={t.occurredOn}/><span className="finance-activity-description"><strong>{outgoing?"To":"From"} {peer?.name||"Archived account"}</strong><small>{t.memo||"Recorded transfer"}</small></span><strong className={`finance-activity-amount ${outgoing?"is-negative":"is-positive"}`}>{money(outgoing?-t.amount:t.amount,{sign:true,cents:true})}</strong></article>})}{candidates.length>0&&<section className="finance-transfer-candidates"><div className="finance-account-section-title"><UnigentamosIcon role="relationship-map"/><div><h3>Possible transfers</h3><p>Same date and amount, opposite directions, different accounts. Review both entries before treating these as transfers.</p></div></div>{candidates.map(pair=><article key={pair.outgoing.id} className="finance-transfer-candidate"><header><DateBadge value={pair.outgoing.occurredOn}/><strong>{money(Math.abs(signedAccountTransaction(pair.outgoing)),{cents:true})}</strong><span>Possible match</span></header>{[pair.outgoing,pair.incoming].map((entry,i)=><a key={entry.id} href={`/admin/finance/transactions?selected=${encodeURIComponent(entry.id)}`}><span>{i?"To":"From"}</span><strong>{state.accounts.find(a=>a.id===entry.accountId)?.name}</strong><small>{entry.merchant}</small><UnigentamosIcon role="chevron-right" size={16}/></a>)}</article>)}</section>}{!transfers.length&&!candidates.length&&<div className="finance-account-empty"><h3>No transfers found</h3><p>Unique, cleared entries with equal amounts moving out of one account and into another on the same day appear here automatically.</p></div>}</>)}
 {panel("imports",imports.length?<div className="finance-account-ledger">{imports.map(batch=><article className="finance-account-import" key={batch.id}><UnigentamosIcon role="import" size={20}/><div><strong>{batch.sourceFilename}</strong><small>{accountDate(batch.confirmedAt,true)}</small><p>{batch.rows.length} rows · {batch.counts.unreconciled} to review · {batch.counts.rejected} skipped</p></div></article>)}</div>:<div className="finance-account-empty"><UnigentamosIcon role="import"/><h3>No imported statements</h3><p>Use Import CSV in the Accounts toolbar to bring in a statement.</p></div>)}
 {panel("properties",<>{[{title:"Account details",icon:"wallet",facts:[["Name",row.account.name],["Institution",account?.institution||"Not recorded"],["Account type",row.account.kind],["Ending in",account?.mask?`••${account.mask.replace(/^[•*]+/,"")}`:"Not recorded"]]},{title:"Balance & connection",icon:"link",facts:[["Balance source",source],["Current balance",money(row.account.balance,{cents:true})],["Balance dated",accountDate(account?.balanceAsOf)],["Last retrieved",accountDate(account?.balanceRetrievedAt,true)]]},{title:"Organization",icon:"briefcase",facts:[["Used for",account?.entityScope==="business"?"Business":"Personal"],["Currency",account?.currency||"USD"]]}].map(section=><section className="finance-account-property-section" key={section.title}><h3><UnigentamosIcon role={section.icon} size={18}/>{section.title}</h3><dl>{section.facts.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>)}</>)}
 </div>
}
