import type { Calendar, EventGroup } from "./types";

export const GROUP_ICONS = [
  "briefcase",
  "university",
  "person",
  "routine",
  "travel",
  "star",
  "goal",
  "users",
  "reminder",
  "module-projects",
  "module-notes",
  "module-media",
  "module-resources",
  "module-finance",
  "birthday",
  "location",
  "organization",
  "clock",
  "interaction-milestone",
  "hometown",
  "partner",
  "active",
  "dormant",
  "dog",
  "walk",
  "feed",
  "droplet",
  "car",
  "travel-van",
  "travel-plane",
  "travel-train",
  "travel-boat",
  "travel-bus",
  "travel-bike",
  "module-map",
  "module-personal",
  "module-reviews",
  "module-vault",
  "build",
  "palette",
  "component",
  "motion",
  "photo-camera",
  "interaction-memory",
  "interaction-note",
  "interaction-catch-up",
  "interaction-meeting",
  "interaction-call",
  "interaction-message",
  "email",
  "website",
  "relationship-map",
  "industry",
  "wallet",
  "piggy-bank",
  "credit-card",
  "banknote",
  "life-dream",
  "sparkles",
  "resource",
  "object",
  "password",
  "review",
  "timeline",
  "follow-up",
  "decision",
];
export const DEFAULT_EVENT_GROUPS: EventGroup[] = [
  { id: "work", name: "Work", color: "#59518B", icon: "briefcase" },
  { id: "school", name: "School", color: "#A17B35", icon: "university" },
  { id: "personal", name: "Personal", color: "#79824E", icon: "person" },
  { id: "wellness", name: "Wellness", color: "#548580", icon: "routine" },
  { id: "travel", name: "Travel", color: "#AD6C55", icon: "travel" },
];
export const calendarGroups = (calendar?: Calendar) =>
  calendar?.groups ?? DEFAULT_EVENT_GROUPS;
export const eventGroup = (calendar: Calendar | undefined, groupId?: string) =>
  calendarGroups(calendar).find((g) => g.id === groupId);
